version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    command: "poetry run python core/manage.py runserver"
  scheduler:
    build: .
    command: "poetry run python core/scheduler.py"
